{% set name = "dist_s1_enumerator" %}
{% set version = "1.0.10" %}
{% set python_min = "3.12" %} 

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dist_s1_enumerator-{{ version }}.tar.gz
  sha256: 9b0fb7b0fc0b0219bf3459d16fab424fb18a67f97c003e1e0af551e9a056aeaa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - asf_search
    - contextily
    - geopandas
    - pandas
    - pandera >=0.24.0
    - pyarrow
    - rasterio
    - requests
    - ruff
    - shapely
    - tenacity
    - tqdm

test:
  imports:
    - dist_s1_enumerator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opera-adt/dist-s1-enumerator
  summary: Enumeration and ops library for the OPERA DIST-S1 project
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - richw7185
    - cmarshak
    - taliboliver
